name: lint-yaml
on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
permissions:
  contents: read

jobs:
  lint-yaml:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Validate Schema
        uses: "authzed/action-spicedb-validate@v1"
        with:
          validationfile: "schema.zed"